# Generated by Django 5.2.10 on 2026-01-12 09:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Target weight in kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('fitness_goal', models.CharField(blank=True, choices=[('WEIGHT_LOSS', 'Weight Loss'), ('WEIGHT_GAIN', 'Weight Gain'), ('MUSCLE_GAIN', 'Muscle Gain'), ('GENERAL_FITNESS', 'General Fitness'), ('ENDURANCE', 'Endurance')], max_length=20, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentary'), ('LIGHTLY_ACTIVE', 'Lightly Active'), ('MODERATELY_ACTIVE', 'Moderately Active'), ('VERY_ACTIVE', 'Very Active'), ('EXTREMELY_ACTIVE', 'Extremely Active')], max_length=20, null=True)),
                ('dietary_preference', models.CharField(blank=True, choices=[('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('PESCATARIAN', 'Pescatarian')], max_length=20, null=True)),
                ('food_allergies', models.JSONField(blank=True, default=list, help_text='List of food allergies')),
                ('health_conditions', models.JSONField(blank=True, default=list, help_text='List of health conditions')),
                ('target_daily_calories', models.IntegerField(blank=True, help_text='Target daily calorie intake', null=True)),
                ('target_timeline_days', models.IntegerField(blank=True, help_text='Days to achieve fitness goal', null=True)),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
