# Generated by Django 5.2.10 on 2026-01-13 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROTEIN", "Protein"),
                            ("CARBS", "Carbohydrates"),
                            ("VEGETABLES", "Vegetables"),
                            ("FRUITS", "Fruits"),
                            ("DAIRY", "Dairy"),
                            ("GRAINS", "Grains"),
                            ("FATS", "Fats & Oils"),
                            ("SNACKS", "Snacks"),
                            ("BEVERAGES", "Beverages"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dietary_type",
                    models.CharField(
                        choices=[
                            ("VEGETARIAN", "Vegetarian"),
                            ("NON_VEGETARIAN", "Non-Vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("PESCATARIAN", "Pescatarian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "serving_size_g",
                    models.DecimalField(decimal_places=1, default=100, max_digits=6),
                ),
                ("calories", models.IntegerField(help_text="Calories per serving")),
                (
                    "protein_g",
                    models.DecimalField(
                        decimal_places=1, help_text="Protein in grams", max_digits=5
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        decimal_places=1, help_text="Carbs in grams", max_digits=5
                    ),
                ),
                (
                    "fats_g",
                    models.DecimalField(
                        decimal_places=1, help_text="Fats in grams", max_digits=5
                    ),
                ),
                (
                    "fiber_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "common_allergens",
                    models.JSONField(
                        blank=True, default=list, help_text="List of common allergens"
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("MORNING_SNACK", "Morning Snack"),
                            ("LUNCH", "Lunch"),
                            ("AFTERNOON_SNACK", "Afternoon Snack"),
                            ("DINNER", "Dinner"),
                            ("EVENING_SNACK", "Evening Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meal_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("total_calories", models.IntegerField(default=0)),
                (
                    "total_protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_carbs_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_fats_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("recipe_instructions", models.TextField(blank=True)),
                (
                    "preparation_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["meal_plan", "order"],
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(help_text="Day number in the nutrition plan"),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("total_calories", models.IntegerField(default=0)),
                (
                    "total_protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_carbs_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_fats_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["nutrition_plan", "day_number"],
            },
        ),
        migrations.CreateModel(
            name="MealFoodItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_g",
                    models.DecimalField(
                        decimal_places=1, help_text="Quantity in grams", max_digits=6
                    ),
                ),
                ("calories", models.IntegerField()),
                ("protein_g", models.DecimalField(decimal_places=1, max_digits=5)),
                ("carbs_g", models.DecimalField(decimal_places=1, max_digits=5)),
                ("fats_g", models.DecimalField(decimal_places=1, max_digits=5)),
                ("order", models.IntegerField(default=0)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="nutrition.meal",
                    ),
                ),
            ],
            options={
                "ordering": ["meal", "order"],
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to="nutrition.mealplan",
            ),
        ),
        migrations.CreateModel(
            name="NutritionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_calories", models.IntegerField(default=0)),
                (
                    "total_protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_carbs_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_fats_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_water_ml",
                    models.IntegerField(default=0, help_text="Water intake in ml"),
                ),
                ("calories_target_met", models.BooleanField(default=False)),
                ("protein_target_met", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nutrition.mealplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="FoodLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("MORNING_SNACK", "Morning Snack"),
                            ("LUNCH", "Lunch"),
                            ("AFTERNOON_SNACK", "Afternoon Snack"),
                            ("DINNER", "Dinner"),
                            ("EVENING_SNACK", "Evening Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_g", models.DecimalField(decimal_places=1, max_digits=6)),
                ("consumed_time", models.TimeField(blank=True, null=True)),
                ("calories", models.IntegerField()),
                ("protein_g", models.DecimalField(decimal_places=1, max_digits=5)),
                ("carbs_g", models.DecimalField(decimal_places=1, max_digits=5)),
                ("fats_g", models.DecimalField(decimal_places=1, max_digits=5)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "nutrition_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_logs",
                        to="nutrition.nutritionlog",
                    ),
                ),
            ],
            options={
                "ordering": ["nutrition_log", "consumed_time"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("WEIGHT_LOSS", "Weight Loss"),
                            ("WEIGHT_GAIN", "Weight Gain"),
                            ("MUSCLE_GAIN", "Muscle Gain"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dietary_preference", models.CharField(max_length=20)),
                (
                    "daily_calories",
                    models.IntegerField(help_text="Daily calorie target"),
                ),
                (
                    "daily_protein_g",
                    models.IntegerField(help_text="Daily protein target in grams"),
                ),
                (
                    "daily_carbs_g",
                    models.IntegerField(help_text="Daily carbs target in grams"),
                ),
                (
                    "daily_fats_g",
                    models.IntegerField(help_text="Daily fats target in grams"),
                ),
                ("daily_fiber_g", models.IntegerField(blank=True, null=True)),
                (
                    "meals_per_day",
                    models.IntegerField(default=3, help_text="Number of meals per day"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mealplan",
            name="nutrition_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_plans",
                to="nutrition.nutritionplan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealplan",
            unique_together={("nutrition_plan", "day_number")},
        ),
    ]
