# Generated by Django 5.2.10 on 2026-01-13 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STRENGTH", "Strength Training"),
                            ("CARDIO", "Cardio"),
                            ("FLEXIBILITY", "Flexibility"),
                            ("HIIT", "HIIT"),
                            ("YOGA", "Yoga"),
                            ("SPORTS", "Sports"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("SHOULDERS", "Shoulders"),
                            ("ARMS", "Arms"),
                            ("LEGS", "Legs"),
                            ("CORE", "Core"),
                            ("FULL_BODY", "Full Body"),
                            ("CARDIO", "Cardio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("NONE", "No Equipment"),
                            ("DUMBBELLS", "Dumbbells"),
                            ("BARBELL", "Barbell"),
                            ("MACHINE", "Machine"),
                            ("RESISTANCE_BAND", "Resistance Band"),
                            ("CABLE", "Cable"),
                            ("BODYWEIGHT", "Bodyweight"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calories_per_minute",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=4),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Step by step instructions"),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_name",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(default=1, help_text="Week number in the plan"),
                ),
                (
                    "focus",
                    models.CharField(
                        help_text="e.g., Upper Body, Cardio, Legs", max_length=100
                    ),
                ),
                ("total_duration_minutes", models.IntegerField(default=60)),
                ("estimated_calories_burned", models.IntegerField(default=300)),
                ("notes", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["workout_plan", "week_number", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.IntegerField(default=3)),
                (
                    "reps",
                    models.IntegerField(
                        blank=True,
                        help_text="Reps per set (leave blank for time-based)",
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration for time-based exercises",
                        null=True,
                    ),
                ),
                (
                    "rest_seconds",
                    models.IntegerField(default=60, help_text="Rest between sets"),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.workoutday",
                    ),
                ),
            ],
            options={
                "ordering": ["workout_day", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                            ("IN_PROGRESS", "In Progress"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("completed_date", models.DateField()),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("calories_burned", models.IntegerField(blank=True, null=True)),
                (
                    "difficulty_rating",
                    models.IntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workouts.workoutday",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_date"],
                "unique_together": {("user", "workout_day", "completed_date")},
            },
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets_completed", models.IntegerField()),
                ("reps_completed", models.IntegerField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "weight_used_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.workoutexercise",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_logs",
                        to="workouts.workoutlog",
                    ),
                ),
            ],
            options={
                "ordering": ["workout_log", "workout_exercise__order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("fitness_goal", models.CharField(max_length=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("3_DAYS", "3 Days per Week"),
                            ("4_DAYS", "4 Days per Week"),
                            ("5_DAYS", "5 Days per Week"),
                            ("6_DAYS", "6 Days per Week"),
                        ],
                        default="3_DAYS",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                (
                    "duration_weeks",
                    models.IntegerField(default=8, help_text="Plan duration in weeks"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workoutday",
            name="workout_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_days",
                to="workouts.workoutplan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workoutday",
            unique_together={("workout_plan", "week_number", "day_name")},
        ),
    ]
